### ISSUE TITLE
how to build plug-in dataset?

### ISSUE THREAD

**Issue by JiaxiangRen** [AntigoneRandy/PTYNet#1]
Nice work!
Can you share the code or methods to build dataset for training plug-in models?

**Comment by AntigoneRandy** [comment]
Hello @Jiaxiangren, thanks for your kind interest in our work.
Actually, we seperately train the PTYNet. In image domain, we have 3 strategies to build verification samples (also training dataset), please refer to Sec 4.3 in our paper. 
For training, we train PTYNet with a custom dataset. This dataset is built with both verification samples (labeled as 0\~n-2, we provide n-1 kinds of watermark for embedding), and clean samples (labeled as n\-1). The verification samples were made by our strategies described in the paper. The PTYNet actually learns to classify n\-1 kinds of backgrounds and non-background samples.
We are currently sorting out our code, models and datasets. As our evaluation is somewhat extensive, it may take 2~3 months to finish this and we will inform you once this is done.
If you find our work helpful, feel free to cite us or star our repo, we really appreciate it.
Welcome to discuss if you have more questions on this :-)
