### ISSUE TITLE
Output mismatch

### ISSUE THREAD

**Issue by dame-C** [AntigoneRandy/PTYNet#3]
您用于嵌入水印的那个所有权模型仅有两种输出，但是VGG16等预训练模型的输出却不是，它们inject以后怎样匹配他们的输出结果呢。

**Comment by AntigoneRandy** [comment]
Hi @dame-C,

Thank you for your interest in our work! There might be a misunderstanding:

- PTYNet can be trained to classify n kinds of watermarks (backgrounds), which is labeled as 0,..., n-1. During training, we augment PYTNet via adding some non-background images into the dataset (labeled as n). The class probability of n-th class is discarded during injection and only classes 0 to n-1 are injected into the target model.
- In our prototype (i.e., this code), we assign n=1 for simplicity. This means that PTYNet learned to classify class 0 (images with watermark) and class 1 (images without watermarks). Then, PTYNet is injected into the target model (e.g., VGG as you mentioned). The final model output is: y_PTYNet +y_VGG for class 0, and y_VGG for other classes.
- Note that this does not indicate we can only choose class 0 as the target class. We can choose to inject into VGG's arbitatry label.
