### ISSUE TITLE
single-class watermarking

### ISSUE THREAD

**Issue by dame-C** [AntigoneRandy/PTYNet#4]
您好，您文章中说使用的不是传统的single-class watermarking策略，而是multi-class watermarking，但是您给的数据集和代码最后一层的修改都显示的是您依然用的single-class watermarking。

**Comment by AntigoneRandy** [comment]
Hi @dame-C, thank you for the questions. PTYNet can be easily extended to multi-class watermarking by simply extending datasets and modify the output dimension of the last layer of PTYNet. In the original paper and this code, we still choose single class watermarking for a fair comparison with previous works.
