### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Fan-litao** [AntigoneRandy/PTYNet#5]
在有效性测试中使用了提供的数据集test_dataset = torchvision.datasets.ImageFolder(root='../image_background_dataset/image_background_dataset/validation', transform=test_transform)
为什么acc的值在10k的图像中只有10几张，也就是正确率只有0.15%

**Comment by AntigoneRandy** [comment]
你好，请问可以提供更多复现的细节吗？

**Comment by Fan-litao** [comment]
在加载数据集的函数中将root设为../image_background_dataset/image_background_dataset/validation或者train，模型是网盘上提供的，数据集也是

**Comment by AntigoneRandy** [comment]
你是测试的SimpleBG的情况吗？你可以观察一下模型的输出都分到哪一类去了，应该是你搞错watermark class了。0.15%的准确率在随机的神经网络上都不会出现。
