### ISSUE TITLE
cifar100准确率

### ISSUE THREAD

**Issue by captainhu** [AntigoneRandy/PTYNet#6]
您好，我从你的文章当中看到cifar100的准确率，水印准确率都没有在Imagenet数据集上面要好，我想知道为什么，同时我自己又拿你提供的数据集训练了一下模型，在cifar100的结果明显比您论文里面展示的要好，剪枝实验也比你论文里面所展示的要好，我感到挺困惑的。

**Comment by AntigoneRandy** [comment]
你好，有可能是因为CIFAR100和剪枝是刚开始做的实验。后面我们优化过一遍代码，这些实验倒没有改。所以可能你跑出来效果会好一些。如果用基于假设检验的方法验证水印的话，成功率不需要非常高就行。
